---
- name: pkgs...
  package: name={{item}} state=latest
  with_items:
    - emacs
    - emacs-goodies

- name: install emacs modes/settings
  copy: dest=/usr/share/emacs/site-lisp/site-start.d/{{item}} src={{item}}
  with_items:
    - 49myemacs.el
    - 50melpa.el
    - 50mycpp.el
    - 50python.el
