---
- include_vars: "{{item}}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- name: Debian
  when: ansible_os_family == 'Debian'
  include: Debian.yml

- name: Fedora
  when: ansible_distribution == 'Fedora'
  include: Fedora.yml

- name: EL
  when: ansible_os_family == 'RedHat' and ansible_distribution != 'Fedora'
  include: EL.yml

- name: install emacs modes/settings
  copy: dest={{emacs_site_d}} src={{item}}
  with_items:
    - 49myemacs.el
    - 50melpa.el
    - 50mycpp.el
    - 50python.el
